version: "3.8"
services:
  rabbitmq:
    restart: always
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 1234
    volumes:
      - "./data:/var/lib/rabbitmq"
      - "./definitions.json:/etc/rabbitmq/definitions.json"
