name: mongodb_docker
services:
  mongodb-community-server:
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    image: 'mongodb/mongodb-community-server:latest'
    environment:
      MONGO_INITDB_DATABASE: myuser
      MONGO_INITDB_USERNAME: myuser
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234

