version: "3.8"
services:
  mysql:
    restart: always
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - "./data:/var/lib/mysql"
      - "./initdb.d:/docker-entrypoint-initdb.d"